### ISSUE TITLE
Function pointers are implicitly convertible from literal 0

### ISSUE THREAD

**Issue by akrzemi1** [viboes/std-make#1]
I remember our conversation from a while ago, and I wanted to record it here also. If the `in_place` is represented as a pointer to function, it is always possible to initialize it with the literal 0, thus adding lots of confusion:

```
optional<rational<BigInt>> or{0};
```

I may be thinking that I am creating a `BigInt` of value 0, but instead I am triggering the `in_place` constructor with unpredictable behavior. I recently needed to fix a similar issue `boost::optional`.

Perhaps instead of function pointers you could use variable templates to achieve a similar goal?

Or perhaps you could add yet another overload that would be a worse match than a constructor taking `T`, but a better match than the `in_place` constructor, and would intercept the attempts to pass constant `0` and thus prevent the bug?

**Comment by viboes** [comment]
I had a variable template up to yesterday :). I don't mind to rollback this change.

**Comment by viboes** [comment]
I have update the proposal rolling back the `in_place` `optional` changes. I've replaced the `in_place` by `in_place_f` for `any`.

https://github.com/viboes/std-make/commit/71cfef2c44447f9390124d2ac3ed9a59426fbc9a 

Please let me know if this fixes the issue.
Any additional comments are welcome.

**Comment by akrzemi1** [comment]
So, `in_place` remains a 'tag' class. This fixes an issue for `optional`. If I read correctly, a similar issue is still present for `any`. Since `in_place_f` is a function pointer, I gather that it is possible to do this:

```
std::any a (0);
```

But perhaps for `any` it is not that much of an issue, as there is no `T` in sight that could add to confusion.

But what is supposed to happen when I type:

```
std::any a (nullptr);
```

?

**Comment by viboes** [comment]
The parameter `in_place_t (*)(undefined<T>)` can not be deduced from `0` neither from `nullptr`. This is not the case for `in_place_t (*)()`so we can not use it for optional.

**Comment by viboes** [comment]
Agustin has found a way to have in_place for both optional and any :)

https://github.com/eggs-cpp/variant/issues/8#issuecomment-138346548

**Comment by K-ballo** [comment]
...and the upcoming variant!

**Comment by viboes** [comment]
Moving to references has no the issue.
