### ISSUE TITLE
Defect in d0323r2 Expected: Needs a valueless due to exception state unlike variant

### ISSUE THREAD

**Issue by ned14** [viboes/std-make#17]
It doesn't yet specify what will be done if you try accessing an expected which is valueless due to exception. std::variant throws bad_variant_access, should Expected throw bad_expected_access<void> as that exception type can never be otherwise thrown?

**Comment by viboes** [comment]
There is no valueless in expected dur to exception.

**Comment by ned14** [comment]
Having re-read the section on the "never empty guarantee", I think I now understand what you mean. What you mean is that if neither of types T and E provide a nothrow move constructor, you expand the storage for Expected to be double the larger of the two, and use Antony's double buffer technique to avoid ever needing to destroy the previous state before constructing the new state. This eliminates the potential for a value due to exception state completely.

If this is correct, you need to change the description text in d0323r2 to say exactly what I just said so it is clear. I was confused by your current wording, and so will therefore be others.

**Comment by viboes** [comment]
No, I don't expand it as Error must be not-throw movable and no-throw assignable.
