### ISSUE TITLE
Defect in d0323r2 Expected: Implicit conversion from T cannot be combined with ordering operators

### ISSUE THREAD

**Issue by ned14** [viboes/std-make#18]
Feedback from ACCU was pretty clear the audience would prefer implicit construction for both E and T where E and T are not constructible into one another. I know you dislike that, and I entirely see your reasoning.

However they were very clear they would far prefer implicit construction from T over Expected being default usable in associative containers. After all, if you really want to store Expected in one of those, you can define custom comparison and hash functions for the STL container. They don't need to be free functions.

**Comment by viboes** [comment]
The first paragraph has nothing to be with the title.

expected is implicitly convertible from T already.

What is the issue? that you want operator < to be removed?

**Comment by ned14** [comment]
> What is the issue? that you want operator < to be removed

The defect is you cannot have both as is currently proposed.

One resolution is always explicit construction via make_expected. Another is to remove the comparison operators. I, and the ACCU audience, prefer the latter.

**Comment by viboes** [comment]
This is not a more defect to the current situation for optional. It is defined like it is. It has the gotcha described by Andrzej.

The paper already mention it and it is up to the committee to decide. My suggestion is to have explicit constructors. I can understand that some prefer to remove the comparison operators, but I aside the failing intents of Tony Van Eerd I have no see any paper trying to fix this issue in optional.

If you consider that this is an issue that must be addressed by the committee please write a paper or at least post a mail in the std-proposal ML. We have time until expected will integrate a TS or the IS.

**Comment by viboes** [comment]
We have removed the comparison operators on the last proposal.
