### ISSUE TITLE
Enhancement in d0323r2 Expected: Missing member functions

### ISSUE THREAD

**Issue by ned14** [viboes/std-make#19]
I still think these would be especially useful:

* .error_or()
* .has_error()

There is also an argument for .index(), .visit() and the other useful member functions from std::variant, but those aren't as useful as the above.

**Comment by viboes** [comment]
There is no valueless_by_exception() because there is no valueless state :)

The other are already in the Open points. I will wait for the review in Toronto.

**Comment by viboes** [comment]
error_or() would be associated to ValuedOrError types and would be a non-member function.

We could have as well has_error as the opposite of has_value in this category of types, as well as non-member function.
