### ISSUE TITLE
D0032R2 Appendix nits

### ISSUE THREAD

**Issue by K-ballo** [viboes/std-make#2]
The first row misses an argument for the 3rd constructor parameter, `char`, in all but one case. The empty line moved up.

The last row is ill-formed, `any` cannot be a literal type because it has a non-trivial destructor. The _WITH_ row should read:

```
any a; // (at namespace scope) constant initialization
```

**Comment by viboes** [comment]
You are right.

**Comment by K-ballo** [comment]
The first row is still not quite correct. There's two definitions of `Foo`, and now they differ. The other rows are passing the `char` argument, so it might be easier to retain it and just fix the first row.

**Comment by K-ballo** [comment]
Thanks
