### ISSUE TITLE
Enhancement in d0323r2 Expected: Overload the try keyword to evaluate expression TRY

### ISSUE THREAD

**Issue by ned14** [viboes/std-make#20]
Rust and Swift have the TRY expression operator which is roughly this:

```
expected<T, E> foo();
...
expected<U, E> foo2()
{
  T = try foo();  /* auto temp = foo(); if(!temp) return make_unexpected(temp.error()); temp.value() */
}
```

C++ already has the keyword, it just needs to gain expression semantics. Perhaps some type traits mechanism like the Coroutines TS where you can tell C++ that some custom type has the TRYable concept and it is evaluated and extracted however that custom type is.

The TRY operation is used very frequently when using Expected in real world code. Or, BOOST_OUTCOME_TRY() in my case. Saves typing lots of boilerplate.

**Comment by viboes** [comment]
expected can be adapted to the current coroutine proposal. Gor has an implementation. SO that you could use await on expected.

**Comment by ned14** [comment]
> expected can be adapted to the current coroutine proposal. Gor has an implementation. SO that you could use await on expected.

I think the await operator is now called something like co_await. Either way, it is not descriptive, the await operation implies some form of waiting or suspension. A try operator has no such implication, it is clearly synchronous.

But in terms of implementation machinery, I very much agree the same machinery can be reused. And the try statement now also becoming an expression is safe for backwards compatibility.

**Comment by viboes** [comment]
You can think what ever you want. await doesn't implies waiting or suspension at least not as defined in the TS.
I have or had a EXPECT in the original proposal as well and I know that others would like another operator that doesn't has wait on the name. Maybe we need just to rename co-awaiy by try :) 

Please be free to write an independent paper for this enhancement. Adding more things to the proposal wouldn't help to adopt it.
