### ISSUE TITLE
`product_type::insert` is unimplementable

### ISSUE THREAD

**Issue by pdimov** [viboes/std-make#21]
... because its return type depends on the function argument `i`, which is not a constant expression. It should take `std::size_t I` as a first template parameter instead.

FWIW, I have `tuple_for_each` in mp11:

https://rawgit.com/pdimov/mp11/develop/doc/html/mp11.html#mp11.reference.tuple_for_each

and I would suggest that these algorithms should be similarly prefixed with `tuple_` instead of `product_type::` and that they should work on tuple-like types, rather than introducing a new and unnecessary "product type" concept.

I would also suggest `constexpr std::size tuple_size(Tp&& tp)` instead of `is_empty`.

Finally, isn't `front(tp)` an alias of `get<0>(tp)`?

**Comment by viboes** [comment]
I don't see why `product_type::insert` is unimplementable, it has a template parameter `size_t N` which is know at compile time. 

The algorithm is susceptible to work with *ProductTypes* which include types that support structured binding (this includes c-arrays, tuple-like types and types that are quite close to aggregate types). The library doesn't takes in account the part that must be generated by the compiler (or reflection if some one is able to do it) for aggregate types.
For me the concept is necessary.

is_empty and front are not really necessary. These are just function with more intent.

**Comment by pdimov** [comment]
Well, `insert( tuple<float>{ 3.14f }, 0, 4 )` returns `tuple<int, float>{ 4, 3.14f }`, but `insert( tuple<float>{ 3.14f }, 1, 4 )` should return `tuple<float, int>{ 3.14f, 4 }`. Note how the return type changes depending on the value of the second argument. This can't be done.

**Comment by viboes** [comment]
Here it is the signature.

```  template <size_t N, class ProductType, class T
  , class = enable_if_t< is_product_type_v<meta::uncvref_t<ProductType>>  >
  >
  constexpr auto insert(ProductType&& pt, T&& x)
```

There is no index in my insert function.

This shouldn't compile `insert( tuple<float>{ 3.14f }, 0, 4 )`

You need
```
auto t = insert<0>( tuple<float>{ 3.14f }, 4 );
```

**Comment by pdimov** [comment]
I was looking at https://github.com/viboes/std-make/blob/master/doc/proposal/reflection/ProductTypeAlgorithms.md#proposed-wording

which does have an index, at least in the synopsis. It's probably outdated.

**Comment by viboes** [comment]
My bad. I need to fix it.

An alternative could be to have an `intergral_constant<size_t, N>` as function parameter.

**Comment by viboes** [comment]
Fixed in https://github.com/viboes/std-make/blob/master/doc/proposal/reflection/p0649r0.md
