### ISSUE TITLE
expeced2 is disabled with GCC

### ISSUE THREAD

**Issue by FSMaxB** [viboes/std-make#35]
Is there a reason for GCC being excluded?

https://github.com/viboes/std-make/blob/b36d66d6713cfee83f0f2f886e80725e68d89018/include/experimental/fundamental/v3/expected2/expected.hpp#L20

It has been working fine for me so far with GCC 8 at least.

**Comment by viboes** [comment]
I guess that it is because with gcc-7.3 (the last I had installed) is not working.
Please, if it works with gcc-8.1 provide a patch and I would accept it.

I'll try later gcc-8.1

BTW the commit you signaled, is not the one that restricted it to clang :)

**Comment by FSMaxB** [comment]
> BTW the commit you signaled, is not the one that restricted it to clang :)

I know, that is just a permanent link provided by GitHub. The commit is in there so that the line number keeps on referring to the same line, even if you commit changes on the master branch.

**Comment by viboes** [comment]
See https://github.com/viboes/std-make/pull/36
