### ISSUE TITLE
P0197R0 missing tuple_element_t template alias?

### ISSUE THREAD

**Issue by cppljevans** [viboes/std-make#9]
template <>
      struct tuple_element<i, C> { using type = Ti; }    // for i in 0..N-1

```
template <size_t I>
  constexpr tuple_element_t<I, C>& get(C& c) noexcept;
```

I don't see the tuple_element_t definition.  I assume it's:

  template<size_t I, typename C>
  using tuple_element_t = tuple_element<i,C>::type;

Could that be added just to be clear.  (I actually missed seeing
the _t and was about to ask about missing ::type in
the get declaration).

**Comment by cppljevans** [comment]
OOPS.  I should have thought to check whether it's already in standard, and it is as
shown here:

http://en.cppreference.com/w/cpp/utility/tuple/tuple_element

Sorry for noise.

**Comment by viboes** [comment]
No problem.
